export const colleges = [
  "Indian Institute of Technology",
  "National Institute of Technology",
  "Delhi University",
  "Mumbai University",
  "Other",
];

export const teamNames = [
  "def_Straw Hat Crew",
  "def_Grand Line Buccaneers",
  "def_New World Nomads",
  "def_Thousand Sunny Pirates",
  "def_Devil Fruit Dynasty",
  "def_One Piece Legends",
  "def_Log Pose Navigators",
  "def_Eternal Voyage Crew",
  "def_Red-Haired Renegades",
  "def_Pirate King's Legacy",
  "def_Raftel Runners",
  "def_Sea King Syndicate",
  "def_Wano Warriors",
  "def_Sky Island Adventurers",
  "def_Revolutionary Corsairs",
  "def_Grand Line Marauders",
  "def_East Blue Buccaneers",
  "def_Yonko's Emissaries",
  "def_Pirate's Paradise Crew",
  "def_One Piece Outlaws",
  "def_Mugiwara Raiders",
  "def_Sabaody Shadows",
  "def_Impel Down Escapees",
];

export const pfp = [
  { src: "/pfp/luffy.jpeg" },
  { src: "/pfp/nami.jpeg" },
  { src: "/pfp/robin.jpeg" },
  { src: "/pfp/zoro.jpeg" },
  { src: "/pfp/sanji.jpeg" },
  { src: "/pfp/jimbei.jpeg" },
  { src: "/pfp/usopp.jpeg" },
  { src: "/pfp/chopper.jpeg" },
  { src: "/pfp/brook.jpeg" },
  { src: "/pfp/gear_5.jpg" },
];
