export const colleges = [
  "Akshaya College, Puttur",
  "Alva's College, Moodubidre",
  "Canara College, Mangalore",
  "Carmel Degree College, Bantwal",
  "Dr. NSAM First Grade College, Nitte",
  "Govinda Das College, Surathkal",
  "Govt. First Grade College (GFGCU), Uppinangady",
  "Mahatma Gandhi Memorial College, Udupi",
  "Manjunatha Pai Memorial Government First Grade College, Karkala",
  "Maps College, Mangalore",
  "Nehru Memorial College (NMC), Sullia",
  "Padua Degree College, Mangalore",
  "Poornaprajna College[PPC], Udupi",
  "Sacred Heart College, Madanthyar",
  "SDM College of Business Management, Mangalore",
  "Sharada College, Mangalore",
  "Shree Devi College, Mangalore",
  "Shree Devi College of Information Science, Mangalore",
  "Sri Bhuvanendra College, Karkala",
  "Sri Dhavala College, Moodabidri",
  "Sri Mahaveera College, Moodbidri",
  "Sri Ramakrishna College, Mangalore",
  "Sri Venkataramana Swamy College, Bantwal",
  "Srinivas First Grade College, Mangalore",
  "Srinivas Institute of Computer Science and Information Science, Mangalore",
  "St. Agnes College, Mangalore",
  "St. Aloysius College (Deemed to be University), Mangalore",
  "St. Philomena College, Puttur",
  "University College, Mangalore",
  "Vivekananda College, Puttur",
  "Yenepoya Institute of Arts, Science, Commerce and Management",
  "Govt First Grade College,Sullia",
];

export const teamNames = [
  "def_Straw Hat Crew",
  "def_Grand Line Buccaneers",
  "def_New World Nomads",
  "def_Thousand Sunny Pirates",
  "def_Devil Fruit Dynasty",
  "def_One Piece Legends",
  "def_Log Pose Navigators",
  "def_Eternal Voyage Crew",
  "def_Red-Haired Renegades",
  "def_Pirate King's Legacy",
  "def_Raftel Runners",
  "def_Sea King Syndicate",
  "def_Wano Warriors",
  "def_Sky Island Adventurers",
  "def_Revolutionary Corsairs",
  "def_Grand Line Marauders",
  "def_East Blue Buccaneers",
  "def_Yonko's Emissaries",
  "def_Pirate's Paradise Crew",
  "def_One Piece Outlaws",
  "def_Mugiwara Raiders",
  "def_Sabaody Shadows",
  "def_Impel Down Escapees",
];

export const pfp = [
  { src: "/pfp/luffy.jpeg" },
  { src: "/pfp/nami.jpeg" },
  { src: "/pfp/robin.jpeg" },
  { src: "/pfp/zoro.jpeg" },
  { src: "/pfp/sanji.jpeg" },
  { src: "/pfp/jimbei.jpeg" },
  { src: "/pfp/usopp.jpeg" },
  { src: "/pfp/chopper.jpeg" },
  { src: "/pfp/brook.jpeg" },
  { src: "/pfp/gear_5.jpg" },
];
