export const colleges = [
  "Indian Institute of Technology",
  "National Institute of Technology",
  "Delhi University",
  "Mumbai University",
  "Other",
];

export const teamNames = [
  "Straw Hat Crew",
  "Grand Line Buccaneers",
  "New World Nomads",
  "Thousand Sunny Pirates",
  "Devil Fruit Dynasty",
  "One Piece Legends",
  "Log Pose Navigators",
  "Eternal Voyage Crew",
  "Red-Haired Renegades",
  "Pirate King's Legacy",
  "Raftel Runners",
  "Sea King Syndicate",
  "Wano Warriors",
  "Sky Island Adventurers",
  "Revolutionary Corsairs",
  "Grand Line Marauders",
  "East Blue Buccaneers",
  "Yonko's Emissaries",
  "Pirate's Paradise Crew",
  "One Piece Outlaws",
];
